
### common insert
POST {{BaseURL}}/admin/common/insert
Content-Type: application/json

{
  "table_name": "sys_user",
  "row": {
    "username": "fengjx",
    "pwd": "1234",
    "nickname": "fjx"
  }
}


### common query
POST {{BaseURL}}/admin/common/query
Content-Type: application/json

{
  "table_name": "sys_user",
  "fields": [
    "id",
    "username",
    "nickname",
    "ctime"
  ],
  "order_fields": [
    {
      "field": "ctime",
      "order_type": "desc"
    }
  ],
  "page": {
    "offset": 0,
    "limit": 20,
    "count": 0,
    "query_count": true
  }
}
